version: '3.8'

services:
  dash:
    build: .
    restart: "always"
    command: python src/main.py
    ports:
      - "8080:8080"
    volumes:
      - ./:/home/app/
    depends_on:
      - postgres

  postgres:
    restart: unless-stopped
    image: postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
      - ./.env

volumes:
  postgres_data:
